-- Sync sales lead (owner) from Attio CSV — owner column ONLY, skips rows with no Business Partners
-- 1458 restaurant name mappings

begin;

update public.deals as d
set owner = m.owner, updated_at = now()
from (values
  ('16 charles street - london', 'Knox Dobbins'),
  ('16 charles street - new york', 'Knox Dobbins'),
  ('1742', 'Stefanie Bobinger'),
  ('1925 tequila', 'Blakely Byrd'),
  ('1925 tequila - monaco', 'Blakely Byrd'),
  ('4 charles prime rib', 'Joshua Stern'),
  ('41 caijing', 'Blakely Byrd'),
  ('4200 n lamar blvd (unnamed venue) - austin', 'Blakely Byrd'),
  ('5 hertford street - london', 'Sasha Lambrecht'),
  ('53 - new york city', 'Peter Gosik'),
  ('53 cocktails - new york', 'Peter Gosik'),
  ('5th column pr', 'Blakely Byrd'),
  ('7 cellars', 'Blakely Byrd'),
  ('7r - new york', 'Peter Gosik'),
  ('9 jones', 'Peter Gosik'),
  ('9 jones - new york city', 'Peter Gosik'),
  ('9 orchard - new york', 'Peter Gosik'),
  ('a rich rose', 'Blakely Byrd'),
  ('a16z (andreessen horowitz) - new york, ny', 'Knox Dobbins'),
  ('aazzur', 'Sasha Lambrecht'),
  ('ab inbev', 'Blakely Byrd + Melissa Crane-Baker'),
  ('ab inbev - new york', 'Blakely Byrd'),
  ('aba', 'Joshua Stern'),
  ('abacum - new york', 'Knox Dobbins'),
  ('aburiya raku (chinatown)', 'Joshua Stern'),
  ('ace consultancy', 'Peter Gosik'),
  ('ace consultancy - new york city', 'Peter Gosik'),
  ('acquolina', 'Courtney Kringstein'),
  ('acre', 'Joshua Stern'),
  ('acura', 'Blakely Byrd'),
  ('adalina', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('adda - new york city', 'Sasha Lambrecht'),
  ('addison del mar', 'Jordan Okun'),
  ('admo lifestyle holding', 'Stefanie Bobinger'),
  ('aelfric eden', 'Blakely Byrd'),
  ('aero', 'Blakely Byrd'),
  ('ai fiori - new york', 'Peter Gosik'),
  ('ajax tavern', 'Courtney Kringstein'),
  ('akub - london', 'Peter Gosik'),
  ('alb vodka', 'Blakely Byrd'),
  ('alba', 'Blakely Byrd'),
  ('alba - new york', 'Blakely Byrd'),
  ('alba spiaggia at montauk yacht club', 'Courtney Kringstein'),
  ('alchemy of the spirit', 'Blakely Byrd'),
  ('alemagou', 'Gaby Espejo'),
  ('alimentari beach - montauk', 'Courtney Kringstein'),
  ('alinea', 'Joshua Stern'),
  ('allison', 'Blakely Byrd'),
  ('alma communications', 'Blakely Byrd'),
  ('almine rech', 'Blakely Byrd'),
  ('almont travel - unknown', 'Blakely Byrd'),
  ('alo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('alpha omega winery', 'Blakely Byrd'),
  ('alphamind group', 'Stefanie Bobinger'),
  ('altamarea group', 'Peter Gosik'),
  ('altro', 'Peter Gosik'),
  ('altro - new york', 'Peter Gosik'),
  ('altro paradiso', 'Peter Gosik'),
  ('altro paradiso - new york', 'Peter Gosik'),
  ('altro paradiso - new york city', 'Peter Gosik'),
  ('aman', 'Peter Gosik'),
  ('amante', 'Stefanie Bobinger'),
  ('american lamb board', 'Blakely Byrd'),
  ('amplified marketing', 'Blakely Byrd'),
  ('anabell’s', 'Melissa Crane-Baker'),
  ('anabelle’s', 'Melissa Crane-Baker'),
  ('angel''s envy', 'Blakely Byrd'),
  ('angler', 'Peter Gosik'),
  ('angler - new york', 'Peter Gosik'),
  ('angler - new york city', 'Peter Gosik'),
  ('angler - san francisco', 'Peter Gosik'),
  ('angler sf - san francisco', 'Peter Gosik'),
  ('anima by edo (spring mountain)', 'Joshua Stern'),
  ('anima by edo / edo gastro tapas', 'Joshua Stern'),
  ('anna cannes', 'Natalia Bojanowicz'),
  ('aosta', 'Courtney Kringstein'),
  ('apollo', 'Blakely Byrd'),
  ('arlington', 'Courtney Kringstein + Natalia Bojanowicz + Stefanie Bobinger'),
  ('armitage alehouse', 'Joshua Stern'),
  ('art basel - international (hong kong dial-in suggests multi-region)', 'Peter Gosik'),
  ('art basel - miami', 'Peter Gosik'),
  ('art basel - new york', 'Knox Dobbins'),
  ('arthroto - canada / us', 'Sasha Lambrecht'),
  ('arthur and sons ny italian - new york city', 'Peter Gosik'),
  ('arts club - london', 'Knox Dobbins'),
  ('arts club hotel - london', 'Stefanie Bobinger'),
  ('arva / aman lounge - new york', 'Knox Dobbins'),
  ('asador bastian', 'Joshua Stern'),
  ('asg hospitality', 'Stefanie Bobinger'),
  ('asg hospitality - new york', 'Peter Gosik'),
  ('asg hospitality - united kingdom', 'Stefanie Bobinger'),
  ('ashton at m18', 'Blakely Byrd'),
  ('assouline', 'Blakely Byrd'),
  ('aston martin', 'Blakely Byrd'),
  ('ataboy', 'Joshua Stern'),
  ('aterra travel - hong kong', 'Sasha Lambrecht'),
  ('atomix', 'Joshua Stern'),
  ('atrbute / the supper club / surface media - new york', 'Blakely Byrd'),
  ('au cheval', 'Joshua Stern'),
  ('au cheval - new york', 'Peter Gosik'),
  ('aurora', 'Stefanie Bobinger'),
  ('aurora - london', 'Stefanie Bobinger'),
  ('auryn studio', 'Blakely Byrd'),
  ('avaline', 'Blakely Byrd'),
  ('avea life - united kingdom', 'Stefanie Bobinger'),
  ('azur wines', 'Blakely Byrd'),
  ('bacardi', 'Blakely Byrd + Melissa Crane-Baker'),
  ('baccarat', 'Blakely Byrd'),
  ('baccarat - new york', 'Blakely Byrd'),
  ('baccarat: the list', 'Blakely Byrd'),
  ('backbird vineyards', 'Blakely Byrd'),
  ('bad roman', 'Joshua Stern'),
  ('bagatelle', 'Courtney Kringstein'),
  ('bagatelle group', 'Sasha Lambrecht'),
  ('bagatelle group london', 'Sasha Lambrecht'),
  ('bagatelle restaurants', 'Courtney Kringstein'),
  ('balenciaga', 'Blakely Byrd'),
  ('bar chimera', 'Joshua Stern'),
  ('bar chimera - <unknown>', 'Peter Gosik'),
  ('bar tutto', 'Joshua Stern'),
  ('bardot brasserie', 'Joshua Stern'),
  ('barton & gray', 'Blakely Byrd'),
  ('basel', 'Knox Dobbins'),
  ('bathtub gin - new york', 'Peter Gosik'),
  ('bathtub gin - new york city', 'Peter Gosik'),
  ('battalion pr', 'Blakely Byrd'),
  ('bavel', 'Jordan Okun'),
  ('bavette''s', 'Joshua Stern'),
  ('bavette''s - new york', 'Blakely Byrd'),
  ('bavette''s steakhouse & bar', 'Joshua Stern'),
  ('bazaar meat (palazzo / venetian)', 'Joshua Stern'),
  ('bde&co', 'Blakely Byrd'),
  ('be real', 'Blakely Byrd + Melissa Crane-Baker'),
  ('beach house', 'Stefanie Bobinger'),
  ('beamsuntory', 'Blakely Byrd'),
  ('beaumarly group', 'Stefanie Bobinger'),
  ('beefbar nyc', 'Courtney Kringstein'),
  ('belvedere', 'Stefanie Bobinger'),
  ('bemelmans', 'Joshua Stern'),
  ('bend goods', 'Blakely Byrd'),
  ('bestia', 'Jordan Okun'),
  ('betty booze', 'Blakely Byrd + Melissa Crane-Baker'),
  ('beverly hills hotel - polo lounge', 'Joshua Stern'),
  ('beyond members club - miami', 'Knox Dobbins'),
  ('bfa', 'Blakely Byrd'),
  ('bhb private', 'Knox Dobbins'),
  ('bhb private - new york', 'Knox Dobbins'),
  ('big mama group', 'Stefanie Bobinger'),
  ('billionaire restaurant & club porto cervo', 'Stefanie Bobinger'),
  ('black coffee - <unknown>', 'Peter Gosik'),
  ('blackstone', 'Knox Dobbins'),
  ('blakely', 'Blakely Byrd'),
  ('blakely - <unknown>', 'Blakely Byrd'),
  ('bleecker street tavern - new york', 'Peter Gosik'),
  ('blossom @ aria', 'Joshua Stern'),
  ('bmf - lamborghini', 'Ava Dagres + Blakely Byrd'),
  ('bmf - marriott luxury residences', 'Blakely Byrd + Melissa Crane-Baker'),
  ('bob bob ricard - london', 'Peter Gosik'),
  ('bob bob ricard soho', 'Peter Gosik'),
  ('bocca di lupo', 'Courtney Kringstein + Natalia Bojanowicz + Stefanie Bobinger'),
  ('bocci', 'Blakely Byrd'),
  ('boia de', 'Joshua Stern'),
  ('boia de miami', 'Joshua Stern'),
  ('boka', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('boka - chicago', 'Peter Gosik'),
  ('bolin', 'Blakely Byrd'),
  ('bom - new york', 'Peter Gosik'),
  ('bombay cru', 'Blakely Byrd'),
  ('bond st', 'Joshua Stern'),
  ('bosq', 'Courtney Kringstein'),
  ('bottarga', 'Stefanie Bobinger'),
  ('bouchon racine', 'Peter Gosik'),
  ('bouchon racine - london', 'Peter Gosik'),
  ('bouchon racine - unknown', 'Peter Gosik'),
  ('bouchon racine; cote miami; zenyara - chicago; miami', 'Peter Gosik'),
  ('bourbon steak miami', 'Joshua Stern'),
  ('bowery group', 'Courtney Kringstein'),
  ('braun x amazon: design dialogue panel', 'Blakely Byrd'),
  ('breitling', 'Blakely Byrd'),
  ('breville', 'Blakely Byrd'),
  ('brex', 'Blakely Byrd + Melissa Crane-Baker'),
  ('bricoleur vineyards', 'Blakely Byrd'),
  ('bricoleur vineyards - new york', 'Blakely Byrd'),
  ('broadway restaurant group', 'Peter Gosik'),
  ('brooklyn grange - brooklyn, ny', 'Blakely Byrd'),
  ('bubbles of britain', 'Blakely Byrd'),
  ('bulgari', 'Blakely Byrd'),
  ('bulleit', 'Blakely Byrd'),
  ('byredo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('c as in charlie', 'Peter Gosik'),
  ('c as in charlie - new york', 'Peter Gosik'),
  ('cactus & co - dallas', 'Blakely Byrd'),
  ('cactus club cafe', 'Knox Dobbins'),
  ('cactus club cafe - vancouver', 'Knox Dobbins'),
  ('cafe carmellini - new york city', 'Peter Gosik'),
  ('cafe kitsune - paris', 'Stefanie Bobinger'),
  ('cafe kitsune opera - paris', 'Stefanie Bobinger'),
  ('cafe kitsune palais royal - paris', 'Stefanie Bobinger'),
  ('cakebread', 'Blakely Byrd'),
  ('calissa', 'Peter Gosik'),
  ('calissa - new york', 'Peter Gosik'),
  ('campari', 'Blakely Byrd'),
  ('campo de fiore', 'Courtney Kringstein'),
  ('camron global', 'Blakely Byrd'),
  ('cannes/monaco venues - cannes/monaco', 'Peter Gosik'),
  ('caprice', 'Joshua Stern'),
  ('cara', 'Knox Dobbins'),
  ('carama', 'Joshua Stern'),
  ('caran d''ache', 'Blakely Byrd'),
  ('caran d''ache - new york', 'Blakely Byrd'),
  ('carbone', 'Peter Gosik'),
  ('carbone - new york', 'Peter Gosik'),
  ('carbone (aria)', 'Joshua Stern'),
  ('carbone miami - miami', 'Peter Gosik'),
  ('carbone riviera (bellagio)', 'Joshua Stern'),
  ('caribou club', 'Courtney Kringstein'),
  ('carpaccio', 'Joshua Stern'),
  ('carte blanche', 'Blakely Byrd'),
  ('cartier', 'Blakely Byrd'),
  ('cartier - new york', 'Blakely Byrd'),
  ('casa centinela', 'Blakely Byrd'),
  ('casa centinela 2025-26', 'Blakely Byrd'),
  ('casa centinela 2026-27', 'Blakely Byrd + Melissa Crane-Baker'),
  ('casa cipriani', 'Courtney Kringstein'),
  ('casa cruz', 'Peter Gosik'),
  ('casa cruz - london', 'Peter Gosik'),
  ('casa cruz new york - new york', 'Peter Gosik'),
  ('casa cruz nyc - new york', 'Peter Gosik'),
  ('casa de raku (chinatown)', 'Joshua Stern'),
  ('casa madera - new york', 'Blakely Byrd'),
  ('casa pacha', 'Marc L'),
  ('casa tua', 'Melissa Crane-Baker'),
  ('casa tua aspen', 'Courtney Kringstein'),
  ('casa tua nyc', 'Joshua Stern'),
  ('casazar', 'Blakely Byrd'),
  ('casino nyc', 'Peter Gosik'),
  ('casino nyc - new york city', 'Peter Gosik'),
  ('catch hg', 'Peter Gosik'),
  ('cathedrale (aria)', 'Joshua Stern'),
  ('cathedrale restaurant - new york', 'Peter Gosik'),
  ('caviar kaspia - london', 'Peter Gosik'),
  ('caviar kaspia - paris', 'Stefanie Bobinger'),
  ('caviar kaspia dubai', 'Stefanie Bobinger'),
  ('cavr - los angeles', 'Blakely Byrd'),
  ('cazadores', 'Blakely Byrd'),
  ('cbre', 'Knox Dobbins'),
  ('celeste', 'Sasha Lambrecht'),
  ('celeste - london', 'Sasha Lambrecht'),
  ('cellar door provisions - chicago', 'Peter Gosik'),
  ('chateau d''esclans', 'Blakely Byrd'),
  ('chateau miraval', 'Blakely Byrd'),
  ('chef driven hospitality - new york city', 'Sasha Lambrecht'),
  ('chelsea living room', 'Peter Gosik'),
  ('chelsea living room - new york', 'Peter Gosik'),
  ('chelsea living room - new york city', 'Peter Gosik'),
  ('chez fifi', 'Peter Gosik'),
  ('chez m - new york', 'Knox Dobbins'),
  ('chez ma tente', 'Knox Dobbins'),
  ('chez margaux', 'Knox Dobbins'),
  ('chez margaux - chicago', 'Knox Dobbins'),
  ('chez margaux - new york', 'Knox Dobbins'),
  ('chez margaux - unknown', 'Knox Dobbins'),
  ('chez margaux, casa cipriani, kith ivy - new york', 'Peter Gosik'),
  ('chez zou', 'Joshua Stern'),
  ('chicago', 'Sasha Lambrecht'),
  ('chilewhich', 'Blakely Byrd'),
  ('china grill', 'Joshua Stern'),
  ('china grill management', 'Joshua Stern'),
  ('chinese tuxedo - new york city', 'Peter Gosik'),
  ('chinois', 'Stefanie Bobinger'),
  ('ciccio mio', 'Joshua Stern'),
  ('cipriani', 'Stefanie Bobinger'),
  ('cipriani dolci', 'Courtney Kringstein'),
  ('cipriani dolci dubai mall', 'Courtney Kringstein + Stefanie Bobinger'),
  ('cipriani dolci jumeirah', 'Courtney Kringstein + Stefanie Bobinger'),
  ('cipriani dolci mall of emirates', 'Courtney Kringstein + Stefanie Bobinger'),
  ('cipriani downtown', 'Courtney Kringstein'),
  ('cipriani downtown miami', 'Courtney Kringstein + Stefanie Bobinger'),
  ('cipriani dubai', 'Courtney Kringstein + Stefanie Bobinger'),
  ('cipriani ibiza', 'Courtney Kringstein'),
  ('cipriani las vegas', 'Joshua Stern'),
  ('cipriani london', 'Stefanie Bobinger'),
  ('cipriani london / cipriani ibiza / socialista london', 'Stefanie Bobinger'),
  ('cipriani london / socialista london - london', 'Peter Gosik'),
  ('cipriani mexico city', 'Courtney Kringstein + Stefanie Bobinger'),
  ('ciroc', 'Blakely Byrd'),
  ('cirrus aviation', 'Blakely Byrd + Melissa Crane-Baker'),
  ('cisco / apple', 'Peter Gosik'),
  ('citi', 'Blakely Byrd'),
  ('citi - austin', 'Blakely Byrd'),
  ('citi - hamptons', 'Blakely Byrd'),
  ('citi - new york', 'Blakely Byrd'),
  ('citi - new york / hamptons', 'Blakely Byrd'),
  ('citi bank', 'Blakely Byrd'),
  ('citi bank strata elite', 'Blakely Byrd'),
  ('clap house', 'Stefanie Bobinger'),
  ('clap house ibiza', 'Stefanie Bobinger'),
  ('clap house ibiza - ibiza', 'Stefanie Bobinger'),
  ('clark''s aspen', 'Courtney Kringstein'),
  ('clase azul', 'Blakely Byrd'),
  ('claud', 'Peter Gosik'),
  ('claud - new york', 'Peter Gosik'),
  ('cleanco', 'Blakely Byrd'),
  ('cleo', 'Courtney Kringstein'),
  ('clif family wines', 'Blakely Byrd'),
  ('clique hospitality', 'Blakely Byrd'),
  ('clos du val', 'Blakely Byrd'),
  ('cloud 9 (aspen mountain)', 'Courtney Kringstein'),
  ('coachella - indio', 'Peter Gosik'),
  ('coachella - indio / coachella valley', 'Peter Gosik'),
  ('coachella - indio / los angeles', 'Peter Gosik'),
  ('coachella - indio / palm springs', 'Peter Gosik'),
  ('coachella - los angeles', 'Peter Gosik'),
  ('coachella - new york city', 'Peter Gosik'),
  ('cocktail collection', 'Blakely Byrd'),
  ('concettina capri', 'Joshua Stern'),
  ('concettina naples', 'Joshua Stern'),
  ('concours - new york city', 'Peter Gosik'),
  ('concours club', 'Blakely Byrd + Melissa Crane-Baker'),
  ('concourse club', 'Melissa Crane-Baker'),
  ('contessa', 'Peter Gosik'),
  ('contessa miami - miami', 'Peter Gosik'),
  ('cookshop / vic''s / shuka / shukette / rosie''s', 'Courtney Kringstein'),
  ('cooley llp', 'Knox Dobbins'),
  ('cooley llp - new york', 'Knox Dobbins'),
  ('coqodaq', 'Peter Gosik'),
  ('coqodaq - new york', 'Peter Gosik'),
  ('core club', 'Melissa Crane-Baker'),
  ('core club - new york', 'Knox Dobbins'),
  ('corner bar - new york', 'Peter Gosik'),
  ('corner bar management - miami', 'Peter Gosik'),
  ('corso', 'Peter Gosik'),
  ('corso - new york', 'Blakely Byrd'),
  ('corso management group / coalition / nine till - new york', 'Peter Gosik'),
  ('corso management group / pmi (philip morris international) - austin', 'Blakely Byrd'),
  ('corso millner group', 'Blakely Byrd'),
  ('costa di mare (wynn)', 'Joshua Stern'),
  ('cote', 'Peter Gosik'),
  ('cote - new york', 'Peter Gosik'),
  ('cote korean steakhouse - new york city', 'Peter Gosik'),
  ('cote korean steakhouse (venetian)', 'Joshua Stern'),
  ('cote madison', 'Joshua Stern'),
  ('cote miami - miami', 'Peter Gosik'),
  ('cote ny - new york', 'Peter Gosik'),
  ('cotogna', 'Joshua Stern'),
  ('cotoletta miami', 'Joshua Stern'),
  ('covermanager', 'Peter Gosik'),
  ('coya', 'Stefanie Bobinger'),
  ('coya mayfair - london', 'Stefanie Bobinger'),
  ('coya restaurant group', 'Stefanie Bobinger'),
  ('craft wines', 'Blakely Byrd'),
  ('crane club - new york', 'Peter Gosik'),
  ('creative restaurant group', 'Sasha Lambrecht'),
  ('creative restaurant group - london', 'Sasha Lambrecht'),
  ('creative restaurant group (crg) - london', 'Stefanie Bobinger'),
  ('creative restaurant group (crg) - phoenix', 'Sasha Lambrecht'),
  ('creative restaurant group (crg) - united kingdom', 'Stefanie Bobinger'),
  ('crg (creative restaurant group) - phoenix', 'Sasha Lambrecht'),
  ('crown shy', 'Peter Gosik'),
  ('crown shy - new york', 'Peter Gosik'),
  ('crying tiger', 'Joshua Stern'),
  ('cucina - new york', 'Peter Gosik'),
  ('cucina alba', 'Peter Gosik'),
  ('cucina alba - new york', 'Peter Gosik'),
  ('cucina alba - new york city', 'Peter Gosik'),
  ('cucina urbana', 'Peter Gosik'),
  ('cut', 'Jordan Okun'),
  ('cybex', 'Blakely Byrd'),
  ('cybex - new york', 'Blakely Byrd'),
  ('d.ream international', 'Courtney Kringstein'),
  ('da toscano', 'Peter Gosik'),
  ('da toscano - new york', 'Peter Gosik'),
  ('da vittorio', 'Stefanie Bobinger'),
  ('daka daka', 'Sasha Lambrecht'),
  ('daka daka - london', 'Sasha Lambrecht'),
  ('daka daka - new york', 'Sasha Lambrecht'),
  ('dalia boston - boston', 'Peter Gosik'),
  ('danny''s - new york', 'Sasha Lambrecht'),
  ('danny''s - new york city', 'Sasha Lambrecht'),
  ('danny''s / the joyce - new york', 'Sasha Lambrecht'),
  ('danny''s nyc - new york', 'Sasha Lambrecht'),
  ('dante - new york city', 'Peter Gosik'),
  ('dante at the snow lodge', 'Courtney Kringstein'),
  ('dante nyc - new york city', 'Peter Gosik'),
  ('dante west village', 'Peter Gosik'),
  ('dante west village - new york', 'Peter Gosik'),
  ('dante west village - new york city', 'Peter Gosik'),
  ('daou vineyards', 'Blakely Byrd'),
  ('das tschecherl', 'Blakely Byrd'),
  ('datasite - new york', 'Knox Dobbins'),
  ('david yurman', 'Blakely Byrd'),
  ('davidsonkempner capital management - new york', 'Knox Dobbins'),
  ('death & co', 'Joshua Stern'),
  ('deep eddy', 'Blakely Byrd'),
  ('delilah', 'Joshua Stern'),
  ('delmonico''s', 'Peter Gosik'),
  ('delmonico''s - new york', 'Peter Gosik'),
  ('dentsu', 'Blakely Byrd'),
  ('department pr', 'Blakely Byrd'),
  ('desert / rodeo nights - las vegas', 'Peter Gosik'),
  ('desert nights - las vegas', 'Peter Gosik'),
  ('desert nights / rodeo nights - las vegas', 'Peter Gosik'),
  ('desert/rodeo nights - las vegas', 'Peter Gosik'),
  ('diageo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('dimmi dimmi', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('din tai fung', 'Courtney Kringstein'),
  ('din tai fung - london', 'Sasha Lambrecht'),
  ('din tai fung century city', 'Joshua Stern'),
  ('din tai fung dubai mall of emirates', 'Joshua Stern'),
  ('din tai fung la', 'Joshua Stern'),
  ('din tai fung midtown', 'Joshua Stern'),
  ('dinnerhq - new york city', 'Sasha Lambrecht'),
  ('dirty french', 'Peter Gosik'),
  ('dirty french - new york', 'Peter Gosik'),
  ('discovery land', 'Knox Dobbins'),
  ('discovery land - new york', 'Knox Dobbins'),
  ('discovery land co - new york', 'Knox Dobbins'),
  ('discovery land co. - new york', 'Knox Dobbins'),
  ('discovery land company', 'Knox Dobbins'),
  ('dolce & gelato catering - unknown', 'Blakely Byrd'),
  ('don angie', 'Joshua Stern'),
  ('don angie, san sabino, bad roman ny, bad roman la', 'Joshua Stern'),
  ('don julio', 'Blakely Byrd'),
  ('donna''s', 'Joshua Stern'),
  ('dorian - london', 'Peter Gosik'),
  ('dorisa', 'Knox Dobbins'),
  ('dorsia flagship - miami', 'Blakely Byrd'),
  ('dorsia in the desert ''26 - desert / coachella valley', 'Peter Gosik'),
  ('dorsia in the desert / coachella 2026 - indio / coachella valley', 'Peter Gosik'),
  ('dorsia nyc office (177 lafayette st) - new york city', 'Peter Gosik'),
  ('dorsia nyc office (in-office tasting) - new york city', 'Peter Gosik'),
  ('dot origin', 'Peter Gosik'),
  ('draft deal', 'Peter Gosik'),
  ('draft kings', 'Blakely Byrd + Melissa Crane-Baker'),
  ('dunsmoor', 'Jordan Okun'),
  ('e by jose andres', 'Joshua Stern'),
  ('e&j gallo winery - miami', 'Blakely Byrd'),
  ('e11even vodka', 'Blakely Byrd'),
  ('early spring', 'Blakely Byrd'),
  ('east hampton grill', 'Joshua Stern'),
  ('echopoint media', 'Blakely Byrd'),
  ('edelman', 'Blakely Byrd'),
  ('eden roc', 'Natalia Bojanowicz'),
  ('edge - new york', 'Knox Dobbins'),
  ('ej gallo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('el chiringuito - new york', 'Peter Gosik'),
  ('el paraguas', 'Courtney Kringstein'),
  ('element 47', 'Courtney Kringstein'),
  ('elevate jet', 'Blakely Byrd'),
  ('ellina', 'Courtney Kringstein'),
  ('emmet''s on grove - new york city', 'Peter Gosik'),
  ('emmett''s on grove', 'Peter Gosik'),
  ('emmett''s on grove - new york city', 'Peter Gosik'),
  ('emora cannes', 'Natalia Bojanowicz'),
  ('empire and co - new york', 'Knox Dobbins'),
  ('employees only', 'Joshua Stern'),
  ('empress gin', 'Blakely Byrd'),
  ('entourage', 'Blakely Byrd'),
  ('entre nos mezcal', 'Blakely Byrd'),
  ('epc', 'Blakely Byrd + Melissa Crane-Baker'),
  ('epstein partners / ubs - new york', 'Knox Dobbins'),
  ('ernest - san francisco', 'Blakely Byrd'),
  ('es blooms', 'Blakely Byrd'),
  ('es torrent', 'Marc L'),
  ('estela', 'Peter Gosik'),
  ('estela - new york', 'Peter Gosik'),
  ('estela - new york city', 'Peter Gosik'),
  ('estelle manor', 'Melissa Crane-Baker'),
  ('esther''s kitchen (arts district)', 'Joshua Stern'),
  ('ethos', 'Blakely Byrd'),
  ('evan funke', 'Jordan Okun'),
  ('evan funke restaurants', 'Jordan Okun'),
  ('evelyn''s table - london', 'Peter Gosik'),
  ('ever', 'Joshua Stern'),
  ('ever / after', 'Joshua Stern'),
  ('ever, after - chicago', 'Sasha Lambrecht'),
  ('expo', 'Knox Dobbins'),
  ('expo - new york', 'Knox Dobbins'),
  ('f05 studio', 'Blakely Byrd'),
  ('f05 studio - new york', 'Blakely Byrd'),
  ('f1rst corp - los angeles', 'Knox Dobbins'),
  ('faena rose', 'Marc L'),
  ('fallow - new york', 'Sasha Lambrecht'),
  ('fallow ny - new york', 'Sasha Lambrecht'),
  ('farfetch - new york', 'Knox Dobbins'),
  ('fat badger', 'Courtney Kringstein'),
  ('fatt pundit - london', 'Peter Gosik'),
  ('feinknopf', 'Blakely Byrd'),
  ('felix', 'Jordan Okun'),
  ('ferrari', 'Blakely Byrd + Melissa Crane-Baker'),
  ('ferraro''s ristorante (off-strip)', 'Joshua Stern'),
  ('ff global group - new york', 'Knox Dobbins'),
  ('fifty three - new york city', 'Peter Gosik'),
  ('fiola mare (wynn) — opening 2025', 'Joshua Stern'),
  ('fisher island', 'Melissa Crane-Baker'),
  ('fisher island club', 'Melissa Crane-Baker'),
  ('fisher island club - miami', 'Knox Dobbins'),
  ('fisher island club - new york', 'Knox Dobbins'),
  ('fitz & co', 'Blakely Byrd'),
  ('flex form', 'Blakely Byrd'),
  ('flos', 'Blakely Byrd'),
  ('flour + water', 'Joshua Stern'),
  ('flowers winery', 'Blakely Byrd'),
  ('floworks', 'Peter Gosik'),
  ('flyfish club - new york', 'Peter Gosik'),
  ('fog & apple', 'Blakely Byrd'),
  ('fog and apple', 'Blakely Byrd'),
  ('four clovers hospitality', 'Courtney Kringstein'),
  ('four seasons / daniel boulud', 'Peter Gosik'),
  ('four seasons toronto - toronto', 'Blakely Byrd'),
  ('freehold - <unknown>', 'Peter Gosik'),
  ('freehold rooftop', 'Peter Gosik'),
  ('french alpine bistro', 'Courtney Kringstein'),
  ('frette', 'Blakely Byrd'),
  ('frette - new york', 'Blakely Byrd'),
  ('frette flagship (new york) - new york', 'Blakely Byrd'),
  ('frette flagship store - new york', 'Blakely Byrd'),
  ('frette flagship store (806 madison ave) - new york', 'Blakely Byrd'),
  ('frevo - new york city', 'Peter Gosik'),
  ('funke', 'Jordan Okun'),
  ('fuze house - unknown', 'Blakely Byrd'),
  ('gabriel kreuther', 'Peter Gosik'),
  ('gabriel kreuther - new york', 'Peter Gosik'),
  ('gaia', 'Stefanie Bobinger'),
  ('gaia miami', 'Joshua Stern'),
  ('gaia monte carlo', 'Marc L'),
  ('galerie on sunset', 'Jordan Okun'),
  ('gap', 'Blakely Byrd'),
  ('gap - new york', 'Blakely Byrd'),
  ('gatekeeper', 'Peter Gosik'),
  ('gatekeeper - <unknown>', 'Peter Gosik'),
  ('gatekeeper - new york', 'Peter Gosik'),
  ('gatekeeper - unknown', 'Peter Gosik'),
  ('gh mumm', 'Blakely Byrd'),
  ('giacomo', 'Courtney Kringstein'),
  ('giacomo ristoranti srl', 'Courtney Kringstein'),
  ('gibsons', 'Joshua Stern'),
  ('gigi', 'Stefanie Bobinger'),
  ('gilt bar', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('giorgio baldi', 'Jordan Okun'),
  ('glennfiddich', 'Blakely Byrd'),
  ('glow recipe', 'Blakely Byrd'),
  ('golden swan', 'Peter Gosik'),
  ('golden unicorn - new york city', 'Peter Gosik'),
  ('goldenvoice - new york', 'Peter Gosik'),
  ('gomry', 'Blakely Byrd'),
  ('goodfin', 'Blakely Byrd'),
  ('goodwin law', 'Knox Dobbins'),
  ('goop', 'Blakely Byrd + Melissa Crane-Baker'),
  ('gotham', 'Blakely Byrd'),
  ('gotham restaurant - new york', 'Peter Gosik'),
  ('gracious hospitality management', 'Peter Gosik'),
  ('gracious hospitality management - new york', 'Peter Gosik'),
  ('greenberg traurig - new york', 'Knox Dobbins'),
  ('greenberg traurig (gt law) - new york', 'Knox Dobbins'),
  ('grupo cappuccino', 'Stefanie Bobinger'),
  ('grupo cappuccino restaurants', 'Stefanie Bobinger'),
  ('grupo hunan', 'Blakely Byrd'),
  ('guggenheim', 'Blakely Byrd'),
  ('gus'' sip & dip', 'Joshua Stern'),
  ('gymkhana', 'Joshua Stern'),
  ('gymkhana (aria)', 'Joshua Stern'),
  ('hacin', 'Blakely Byrd'),
  ('hai sai', 'Courtney Kringstein'),
  ('hakkasan (mgm grand)', 'Joshua Stern'),
  ('hampton - new york', 'Knox Dobbins'),
  ('hamptons', 'Sasha Lambrecht'),
  ('hamptons (market/territory) - hamptons', 'Peter Gosik'),
  ('harry cipriani', 'Courtney Kringstein'),
  ('hasalon', 'Peter Gosik'),
  ('hasalon - new york', 'Peter Gosik'),
  ('hasalon la', 'Jordan Okun'),
  ('hasalon las vegas', 'Joshua Stern'),
  ('hasalon nyc - new york city', 'Peter Gosik'),
  ('hearts & science / chanel - new york', 'Blakely Byrd'),
  ('heavensake', 'Blakely Byrd + Melissa Crane-Baker'),
  ('hedley studios', 'Blakely Byrd'),
  ('helen yarmak', 'Blakely Byrd'),
  ('hell''s kitchen (caesars palace)', 'Joshua Stern'),
  ('hellocara - new york', 'Knox Dobbins'),
  ('hendricks', 'Blakely Byrd'),
  ('her place supper club', 'Peter Gosik'),
  ('hermes', 'Blakely Byrd'),
  ('high noon', 'Blakely Byrd + Melissa Crane-Baker'),
  ('hillstone', 'Joshua Stern'),
  ('hillstone bal harbour', 'Joshua Stern'),
  ('hillstone la', 'Joshua Stern'),
  ('hillstone nyc park ave', 'Joshua Stern'),
  ('hillstone sf', 'Joshua Stern'),
  ('hive - new york', 'Knox Dobbins'),
  ('hmy yachts', 'Blakely Byrd'),
  ('hoexter''s - new york city', 'Peter Gosik'),
  ('hogsalt', 'Joshua Stern'),
  ('hogsalt hospitality', 'Blakely Byrd'),
  ('hogsalt restaurants', 'Courtney Kringstein'),
  ('holiday bar', 'Peter Gosik'),
  ('holiday bar - new york', 'Peter Gosik'),
  ('honor bar beverly hills', 'Joshua Stern'),
  ('hotaling & co', 'Blakely Byrd'),
  ('hotel costes', 'Stefanie Bobinger'),
  ('hotel investment conference', 'Sasha Lambrecht'),
  ('hotel jerome', 'Courtney Kringstein'),
  ('house of prime rib', 'Joshua Stern'),
  ('hue & cry agency (on behalf of unnamed vodka brand) - new york city', 'Blakely Byrd'),
  ('hurlingham club', 'Melissa Crane-Baker'),
  ('i & a agave spirits', 'Blakely Byrd'),
  ('ibiza a la carte - ibiza', 'Blakely Byrd'),
  ('iheart', 'Blakely Byrd'),
  ('iheartmedia', 'Blakely Byrd'),
  ('iheartmedia - new york', 'Blakely Byrd'),
  ('il buco', 'Courtney Kringstein'),
  ('il buco new york', 'Courtney Kringstein'),
  ('il grande', 'Natalia Bojanowicz'),
  ('il riccio - capri, italy', 'Stefanie Bobinger'),
  ('ilili - new york city', 'Peter Gosik'),
  ('index ventures - new york', 'Knox Dobbins'),
  ('indienne new york', 'Sasha Lambrecht'),
  ('indienne new york - new york', 'Peter Gosik'),
  ('indochine', 'Joshua Stern'),
  ('infobip - chicago', 'Peter Gosik'),
  ('intercom - london', 'Peter Gosik'),
  ('internal (dorsia)', 'Peter Gosik'),
  ('island hospitality', 'Stefanie Bobinger'),
  ('ito omakase (fontainebleau)', 'Joshua Stern'),
  ('iwa sake ny office - new york', 'Peter Gosik'),
  ('iyo milano', 'Courtney Kringstein + Joshua Stern'),
  ('iyo omakase', 'Courtney Kringstein + Joshua Stern'),
  ('izakaya @ supermarket of dreams - london', 'Peter Gosik'),
  ('izakaya at supermarket of dreams and tuna fight club', 'Peter Gosik'),
  ('j bar', 'Courtney Kringstein'),
  ('j sheekey', 'Stefanie Bobinger'),
  ('jac''s on bond', 'Peter Gosik'),
  ('jac''s on bond - new york', 'Peter Gosik'),
  ('jackson family wines', 'Blakely Byrd'),
  ('jacob & co', 'Blakely Byrd'),
  ('jacob & co - new york', 'Blakely Byrd'),
  ('jaeger-lecoultre', 'Blakely Byrd'),
  ('jais', 'Marc L'),
  ('jais ibiza', 'Marc L'),
  ('jean georges', 'Joshua Stern'),
  ('jean-georges (aria)', 'Joshua Stern'),
  ('jeju - unknown', 'Peter Gosik'),
  ('jeju noodle bar', 'Peter Gosik'),
  ('jeju noodle bar - new york', 'Peter Gosik'),
  ('jeju noodle bar - unknown', 'Peter Gosik'),
  ('jelani (jelani hutchins-belgrave / the supper club inc.) - new york', 'Peter Gosik'),
  ('jet set group', 'Blakely Byrd'),
  ('jetset livery - new york city', 'Sasha Lambrecht'),
  ('jih pr - arias', 'Blakely Byrd'),
  ('jimmy choo', 'Blakely Byrd'),
  ('jing', 'Courtney Kringstein'),
  ('jing yang - new york', 'Knox Dobbins'),
  ('jks global deal', 'Joshua Stern'),
  ('jks hospitality (gymkhana)', 'Joshua Stern'),
  ('jll (jones lang lasalle) - hamptons', 'Blakely Byrd'),
  ('jo communications', 'Blakely Byrd'),
  ('joe’s seafood, prime steak & stone crab', 'Joshua Stern'),
  ('joel robuchon', 'Joshua Stern'),
  ('johnnie walker', 'Blakely Byrd'),
  ('jondal', 'Natalia Bojanowicz'),
  ('jondal - second location', 'Natalia Bojanowicz'),
  ('jose cuervo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('jose cuervo - mexico city', 'Blakely Byrd'),
  ('jpmorgan chase (jpmc)', 'Knox Dobbins'),
  ('jul''s', 'Stefanie Bobinger'),
  ('jul''s london', 'Stefanie Bobinger'),
  ('jul''s london - london', 'Stefanie Bobinger'),
  ('juls london - london', 'Stefanie Bobinger'),
  ('kabawa - new york city', 'Peter Gosik'),
  ('kaiseki sanga', 'Joshua Stern'),
  ('kame omakase (off-strip)', 'Joshua Stern'),
  ('kappo masa', 'Courtney Kringstein'),
  ('kappo masa & bar masa - new york city', 'Sasha Lambrecht'),
  ('kasama', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('kebab queen - london', 'Peter Gosik'),
  ('kenichi', 'Courtney Kringstein'),
  ('kering group', 'Radhika Bansil'),
  ('ketchy shuby beach', 'Courtney Kringstein'),
  ('ketel one', 'Blakely Byrd + Melissa Crane-Baker'),
  ('ketel one / starpower llc', 'Blakely Byrd'),
  ('khoury''s fine wine & spirits (off-strip)', 'Joshua Stern'),
  ('kilo caviar', 'Blakely Byrd'),
  ('kith ivy - new york', 'Knox Dobbins'),
  ('kitsune - paris', 'Stefanie Bobinger'),
  ('kitty’s cosmopolitan club', 'Joshua Stern'),
  ('kol', 'Courtney Kringstein'),
  ('komodo', 'Joshua Stern'),
  ('konstantin emmetts', 'Peter Gosik'),
  ('koral communications pr', 'Blakely Byrd'),
  ('kreativ flow llc - las vegas', 'Blakely Byrd'),
  ('kuchar', 'Blakely Byrd'),
  ('kwame', 'Andrew Goldberg'),
  ('l.a. libations', 'Blakely Byrd'),
  ('l''abeille', 'Peter Gosik'),
  ('l''abeille - new york', 'Peter Gosik'),
  ('l''abeille - new york city', 'Peter Gosik'),
  ('l''abeille a cote', 'Peter Gosik'),
  ('l''abellie', 'Peter Gosik'),
  ('l''atelier de joel robuchon', 'Joshua Stern'),
  ('l''avenue', 'Stefanie Bobinger'),
  ('la bambola', 'Natalia Bojanowicz'),
  ('la bullona', 'Stefanie Bobinger'),
  ('la fete wine', 'Blakely Byrd'),
  ('la guerite', 'Natalia Bojanowicz'),
  ('la petite maison', 'Natalia Bojanowicz'),
  ('la reserve', 'Natalia Bojanowicz'),
  ('la specialita', 'Marc L'),
  ('la spiga ristorante italiano - palm desert', 'Peter Gosik'),
  ('la torre', 'Natalia Bojanowicz'),
  ('lacma', 'Blakely Byrd'),
  ('ladbroke hall', 'Peter Gosik'),
  ('ladbroke hall - london', 'Peter Gosik'),
  ('lakeside (wynn) / pisces bar & seafare', 'Joshua Stern'),
  ('lalo', 'Blakely Byrd'),
  ('lalo spirits', 'Blakely Byrd'),
  ('lamaii thai (spring mountain)', 'Joshua Stern'),
  ('lamborghini - <unknown>', 'Blakely Byrd'),
  ('langan''s brasserie - london', 'Peter Gosik'),
  ('langosteria', 'Joshua Stern'),
  ('lapaba', 'Jordan Okun'),
  ('laperouse holding (lafayette''s, prunier, univrs & hi ibiza) - paris', 'Knox Dobbins'),
  ('lapo''s', 'Blakely Byrd'),
  ('lapo''s - los angeles', 'Blakely Byrd'),
  ('lapo''s - new york', 'Blakely Byrd'),
  ('las monatanas', 'Courtney Kringstein'),
  ('laurent perrier', 'Blakely Byrd'),
  ('ldv at the maidstone - hamptons', 'Blakely Byrd'),
  ('ldv hamptons - new york / hamptons', 'Blakely Byrd'),
  ('ldv hospitality', 'Blakely Byrd'),
  ('ldv hospitality - new york', 'Blakely Byrd'),
  ('le bernardin', 'Courtney Kringstein'),
  ('le bibloquet', 'Courtney Kringstein'),
  ('le bibloquet nyc', 'Courtney Kringstein'),
  ('le bilboquet hamptons', 'Courtney Kringstein'),
  ('le bilboquet palm beach', 'Courtney Kringstein'),
  ('le cirque (bellagio)', 'Joshua Stern'),
  ('le gratin', 'Peter Gosik'),
  ('le gratin - new york', 'Peter Gosik'),
  ('le jardinier - new york', 'Peter Gosik'),
  ('le jardinier - new york city', 'Peter Gosik'),
  ('le labo', 'Blakely Byrd'),
  ('le pastis', 'Natalia Bojanowicz'),
  ('le pavillon - new york', 'Peter Gosik'),
  ('le pavillon / le gratin - new york', 'Peter Gosik'),
  ('le vague d’or', 'Natalia Bojanowicz'),
  ('le zoo', 'Joshua Stern'),
  ('lea akyuz', 'Stefanie Bobinger'),
  ('legacy club plano - plano', 'Knox Dobbins'),
  ('les amis', 'Melissa Crane-Baker'),
  ('lettuce entertain you', 'Joshua Stern'),
  ('lettuce entertain you deal', 'Joshua Stern'),
  ('leviate air group', 'Blakely Byrd'),
  ('lexus', 'Blakely Byrd + Melissa Crane-Baker'),
  ('lily (plschk.com)', 'Blakely Byrd'),
  ('little prince', 'Peter Gosik'),
  ('little prince - new york', 'Peter Gosik'),
  ('little prince - new york city', 'Peter Gosik'),
  ('little prince / lola taverna - new york', 'Peter Gosik'),
  ('lo scoglio', 'Joshua Stern'),
  ('lobster bar', 'Joshua Stern'),
  ('locanda verde', 'Peter Gosik'),
  ('locanda verde - new york', 'Peter Gosik'),
  ('loewe', 'Blakely Byrd'),
  ('lola - unknown', 'Sasha Lambrecht'),
  ('lola taverna', 'Peter Gosik'),
  ('lola taverna - new york', 'Peter Gosik'),
  ('lola taverna - unknown', 'Peter Gosik'),
  ('london', 'Peter Gosik'),
  ('loring place', 'Peter Gosik'),
  ('loring place - new york', 'Peter Gosik'),
  ('los fuegos - buenos aires', 'Peter Gosik'),
  ('los fuegos by francis mallman', 'Peter Gosik'),
  ('los pantalones', 'Blakely Byrd + Melissa Crane-Baker'),
  ('lotus of siam (commercial center)', 'Joshua Stern'),
  ('louie - london', 'Peter Gosik'),
  ('loulou', 'Knox Dobbins'),
  ('loulou - london', 'Knox Dobbins'),
  ('loulou - paris', 'Knox Dobbins'),
  ('loulou group', 'Courtney Kringstein'),
  ('loulou groupe', 'Knox Dobbins'),
  ('loulou groupe sas', 'Knox Dobbins'),
  ('loulou paris - paris', 'Knox Dobbins'),
  ('loulou''s - <unknown>', 'Sasha Lambrecht'),
  ('loulou''s london - london', 'Knox Dobbins'),
  ('lpm', 'Natalia Bojanowicz'),
  ('lpm restaurant & bar - london', 'Peter Gosik'),
  ('luca hamm - new york', 'Knox Dobbins'),
  ('luca.hamm@gmail.com', 'Knox Dobbins'),
  ('lucien', 'Courtney Kringstein'),
  ('lucky one', 'Blakely Byrd + Melissa Crane-Baker'),
  ('luigi', 'Natalia Bojanowicz'),
  ('lumify', 'Blakely Byrd + Melissa Crane-Baker'),
  ('lure fishbar', 'Joshua Stern'),
  ('lusive decor', 'Blakely Byrd'),
  ('macallan', 'Blakely Byrd'),
  ('mad studio', 'Blakely Byrd'),
  ('madame ushi', 'Courtney Kringstein'),
  ('maestro dobel tequila', 'Blakely Byrd'),
  ('maidstone - new york', 'Blakely Byrd'),
  ('maison close hamptons', 'Courtney Kringstein'),
  ('maison estelle', 'Sasha Lambrecht'),
  ('maison estelle - london', 'Sasha Lambrecht'),
  ('maison premiere', 'Peter Gosik'),
  ('maison premiere - brooklyn', 'Peter Gosik'),
  ('maison sun', 'Sasha Lambrecht'),
  ('maison sun - brooklyn, ny', 'Sasha Lambrecht'),
  ('major food group', 'Peter Gosik'),
  ('major food group - new york', 'Peter Gosik'),
  ('major food group - new york city', 'Peter Gosik'),
  ('major food group (mfg) - new york', 'Peter Gosik'),
  ('major food group (mfg) - new york city', 'Peter Gosik'),
  ('mamo', 'Natalia Bojanowicz'),
  ('mamo - new york city', 'Sasha Lambrecht'),
  ('mano a mano', 'Joshua Stern'),
  ('manya - new york', 'Blakely Byrd'),
  ('maple & ash', 'Joshua Stern'),
  ('marc jacobs', 'Peter Gosik'),
  ('marc jacobs - new york', 'Peter Gosik'),
  ('marea - new york city', 'Peter Gosik'),
  ('marea aspen', 'Courtney Kringstein'),
  ('mark adipietro', 'Peter Gosik'),
  ('maroon (off-strip)', 'Joshua Stern'),
  ('marriott luxury residences', 'Blakely Byrd + Melissa Crane-Baker'),
  ('marriott residences', 'Blakely Byrd'),
  ('martiny''s', 'Peter Gosik'),
  ('martiny''s - new york city', 'Peter Gosik'),
  ('mary lou''s - new york', 'Sasha Lambrecht'),
  ('mary lou''s - unknown', 'Sasha Lambrecht'),
  ('mary lou''s palm beach', 'Courtney Kringstein'),
  ('massara', 'Peter Gosik'),
  ('massara - new york', 'Peter Gosik'),
  ('massara - new york city', 'Peter Gosik'),
  ('matthiason wines', 'Blakely Byrd'),
  ('mattos hospitality', 'Peter Gosik'),
  ('mattos hospitality - new york city', 'Peter Gosik'),
  ('mavericks', 'Courtney Kringstein'),
  ('maximon - <unknown>', 'Stefanie Bobinger'),
  ('maximon - united kingdom', 'Stefanie Bobinger'),
  ('maxwell social', 'Knox Dobbins'),
  ('maybach members club', 'Blakely Byrd'),
  ('maybach ocean club', 'Melissa Crane-Baker'),
  ('mcclaren relocation - new york', 'Blakely Byrd'),
  ('mcl law (mcllp.com)', 'Knox Dobbins'),
  ('medusa', 'Natalia Bojanowicz'),
  ('meduza - new york', 'Peter Gosik'),
  ('meduza mediterrania new york - new york', 'Peter Gosik'),
  ('meduza miami', 'Peter Gosik'),
  ('members club - <unknown>', 'Knox Dobbins'),
  ('members clubs (unspecified) - unknown', 'Knox Dobbins'),
  ('meta ray-ban', 'Blakely Byrd + Melissa Crane-Baker'),
  ('miami', 'Peter Gosik'),
  ('michael mina (bellagio)', 'Joshua Stern'),
  ('microsoft - new york', 'Knox Dobbins'),
  ('mirora', 'Blakely Byrd'),
  ('mirora surfboards', 'Blakely Byrd'),
  ('miru', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('mizumi (wynn)', 'Joshua Stern'),
  ('mml hospitality - austin', 'Blakely Byrd'),
  ('mml hospitality group', 'Blakely Byrd'),
  ('modaconcrete', 'Blakely Byrd'),
  ('mode downtown miami - miami', 'Blakely Byrd'),
  ('modulnova', 'Blakely Byrd'),
  ('moet hennessey', 'Blakely Byrd + Melissa Crane-Baker'),
  ('moet hennessy - new york', 'Blakely Byrd'),
  ('moma group', 'Stefanie Bobinger'),
  ('moma group - <unknown>', 'Stefanie Bobinger'),
  ('moma group - united kingdom', 'Stefanie Bobinger'),
  ('momentum textiles and wallcovering', 'Blakely Byrd'),
  ('momofuku', 'Peter Gosik'),
  ('momofuku - <unknown>', 'Peter Gosik'),
  ('momofuku - new york', 'Peter Gosik'),
  ('momofuku @ the cosmo', 'Joshua Stern'),
  ('momofuku cash will haering', 'Peter Gosik'),
  ('momofuku noodle bar - new york', 'Peter Gosik'),
  ('momofuku noodle bar east village - new york', 'Peter Gosik'),
  ('momofuku noodle bar uptown - new york', 'Peter Gosik'),
  ('momofuku noodle bar uptown - new york city', 'Peter Gosik'),
  ('monkey bar', 'Joshua Stern'),
  ('monsieur dior', 'Courtney Kringstein'),
  ('montauk yacht club', 'Courtney Kringstein'),
  ('monte''s montauk', 'Courtney Kringstein'),
  ('monteverde', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('moon pay', 'Blakely Byrd + Melissa Crane-Baker'),
  ('moonpay', 'Peter Gosik'),
  ('morimoto las vegas', 'Joshua Stern'),
  ('mother wolf', 'Peter Gosik'),
  ('mother wolf - los angeles', 'Peter Gosik'),
  ('mother wolf (resorts world)', 'Joshua Stern'),
  ('mr nice', 'Stefanie Bobinger'),
  ('mr porter', 'Stefanie Bobinger'),
  ('mr porter london - london', 'Stefanie Bobinger'),
  ('musaafer - new york', 'Blakely Byrd'),
  ('musaafer / barlume / the maidstone - new york', 'Blakely Byrd'),
  ('musket room - new york', 'Peter Gosik'),
  ('my world vip - london', 'Sasha Lambrecht'),
  ('na:eun hospitality', 'Andrew Goldberg'),
  ('nami nori la', 'Jordan Okun'),
  ('nammos', 'Stefanie Bobinger'),
  ('nammos - london', 'Stefanie Bobinger'),
  ('nammos - unknown', 'Sasha Lambrecht'),
  ('nammos baja sardinia (phi beach)', 'Stefanie Bobinger'),
  ('nammos dubai', 'Stefanie Bobinger'),
  ('nammos london - london', 'Stefanie Bobinger'),
  ('nassau beach club', 'Stefanie Bobinger'),
  ('natalie o.', 'Blakely Byrd'),
  ('navan', 'Sasha Lambrecht'),
  ('net jets', 'Blakely Byrd + Melissa Crane-Baker'),
  ('neuehouse - <unknown>', 'Knox Dobbins'),
  ('neuehouse - new york city', 'Knox Dobbins'),
  ('neuehouse madison square - new york', 'Knox Dobbins'),
  ('new york', 'Peter Gosik'),
  ('new york city', 'Peter Gosik'),
  ('nina', 'Stefanie Bobinger'),
  ('nine orchard - new york', 'Peter Gosik'),
  ('nine orchard (swan room / corner bar) - new york city', 'Peter Gosik'),
  ('nine orchard: corner bar and swan room', 'Peter Gosik'),
  ('niwaki - unknown', 'Peter Gosik'),
  ('noble 33', 'Peter Gosik'),
  ('nobu', 'Peter Gosik'),
  ('nobu - new york', 'Peter Gosik'),
  ('nobu (caesars palace)', 'Joshua Stern'),
  ('nobu 57', 'Marc L'),
  ('nobu by the beach', 'Joshua Stern'),
  ('nobu chicago', 'Joshua Stern'),
  ('nobu hospitality', 'Marc L'),
  ('nobu la', 'Marc L'),
  ('nobu malibu', 'Marc L'),
  ('nobu miami', 'Joshua Stern'),
  ('nobu restaurants', 'Marc L'),
  ('nobu; cote miami - miami', 'Peter Gosik'),
  ('noema', 'Stefanie Bobinger'),
  ('north miznon', 'Peter Gosik'),
  ('notorious foodie', 'Stefanie Bobinger'),
  ('notorious foodie - new york', 'Stefanie Bobinger'),
  ('nougatine', 'Joshua Stern'),
  ('nyc x design festival', 'Blakely Byrd'),
  ('nyu ifh - new york', 'Sasha Lambrecht'),
  ('nyu ihif - new york', 'Sasha Lambrecht'),
  ('oakley', 'Blakely Byrd + Melissa Crane-Baker'),
  ('ocean house', 'Blakely Byrd'),
  ('ocean house - watch hill, rhode island', 'Blakely Byrd'),
  ('oceano wines', 'Blakely Byrd'),
  ('office partners 360', 'Peter Gosik'),
  ('oiji mi', 'Peter Gosik'),
  ('oiji mi - new york', 'Peter Gosik'),
  ('olipop', 'Blakely Byrd + Melissa Crane-Baker'),
  ('olive + oak - webster groves, mo', 'Peter Gosik'),
  ('omakase room at sushi san', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('one hope wines', 'Blakely Byrd'),
  ('open ap', 'Blakely Byrd + Melissa Crane-Baker'),
  ('openai - new york', 'Knox Dobbins'),
  ('opentable - new york city', 'Peter Gosik'),
  ('opto nyc', 'Courtney Kringstein'),
  ('oracle red bull racing (orbr) - unknown', 'Knox Dobbins'),
  ('orchestra', 'Blakely Byrd'),
  ('orla', 'Joshua Stern'),
  ('ospi venice - los angeles', 'Peter Gosik'),
  ('osteria fiorella (red rock resort)', 'Joshua Stern'),
  ('otherlife', 'Peter Gosik'),
  ('ottolenghi', 'Natalia Bojanowicz'),
  ('overthelux', 'Stefanie Bobinger'),
  ('ovios × studio f. a. porsche', 'Blakely Byrd'),
  ('pachamama', 'Stefanie Bobinger'),
  ('pachamama deal', 'Stefanie Bobinger'),
  ('pachamama group', 'Stefanie Bobinger'),
  ('palm beach club', 'Natalia Bojanowicz'),
  ('palm club', 'Natalia Bojanowicz'),
  ('paper moon', 'Stefanie Bobinger'),
  ('papi steak', 'Joshua Stern'),
  ('parc', 'Courtney Kringstein'),
  ('paris', 'Stefanie Bobinger'),
  ('paris society', 'Stefanie Bobinger'),
  ('paris society - paris', 'Stefanie Bobinger'),
  ('park chinois', 'Stefanie Bobinger'),
  ('passkit', 'Peter Gosik'),
  ('patek philippe - <unknown>', 'Blakely Byrd'),
  ('patek philippe - new york', 'Blakely Byrd'),
  ('patek phillippe', 'Blakely Byrd'),
  ('patron', 'Blakely Byrd'),
  ('paul hastings - new york', 'Knox Dobbins'),
  ('pembroke members club - london', 'Stefanie Bobinger'),
  ('pernod ricard', 'Blakely Byrd'),
  ('pernod ricard/perrier jouet', 'Blakely Byrd + Melissa Crane-Baker'),
  ('peter luger steakhouse', 'Courtney Kringstein'),
  ('petit trois aspen', 'Courtney Kringstein'),
  ('petrossian', 'Blakely Byrd'),
  ('phi restaurant (phi beach)', 'Stefanie Bobinger'),
  ('picasso (closed — replacement: carbone riviera)', 'Joshua Stern'),
  ('piccolo - new york city', 'Sasha Lambrecht'),
  ('piccolo morini', 'Joshua Stern'),
  ('pinecreak cookhouse', 'Courtney Kringstein'),
  ('pinna mayfair', 'Stefanie Bobinger'),
  ('pinna mayfair; belvedere restaurant - london', 'Stefanie Bobinger'),
  ('pinna, belvedere, chelsea grill, wild tavern - london', 'Stefanie Bobinger'),
  ('pizza studio tamaki', 'Joshua Stern'),
  ('pizza studio tamaki les', 'Joshua Stern'),
  ('plage keller', 'Natalia Bojanowicz'),
  ('plump jack wine', 'Blakely Byrd'),
  ('pmc', 'Knox Dobbins'),
  ('pmc - new york', 'Knox Dobbins'),
  ('pmc (via emma moran / the stanza media intro)', 'Knox Dobbins'),
  ('polo bar', 'Marc L'),
  ('polo bar london', 'Courtney Kringstein'),
  ('poppi', 'Blakely Byrd + Melissa Crane-Baker'),
  ('porsche design', 'Blakely Byrd + Melissa Crane-Baker'),
  ('pr consulting', 'Blakely Byrd'),
  ('pr consulting, jenn brady', 'Blakely Byrd'),
  ('prime steakhouse bellagio', 'Joshua Stern'),
  ('principe', 'Peter Gosik'),
  ('principe - new york', 'Peter Gosik'),
  ('principe - new york city', 'Peter Gosik'),
  ('prior world', 'Knox Dobbins'),
  ('prior world - new york', 'Knox Dobbins'),
  ('prive experiences - new york', 'Knox Dobbins'),
  ('promontory - napa', 'Blakely Byrd'),
  ('proof media', 'Blakely Byrd'),
  ('proskauer - new york', 'Knox Dobbins'),
  ('proximo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('proximo spirits', 'Sasha Lambrecht'),
  ('proximo spirits - phoenix', 'Sasha Lambrecht'),
  ('publicus', 'Blakely Byrd'),
  ('purisima tequila', 'Blakely Byrd + Melissa Crane-Baker'),
  ('purple', 'Blakely Byrd'),
  ('quality branded', 'Joshua Stern'),
  ('quince', 'Joshua Stern'),
  ('quinn pr | brugal', 'Blakely Byrd'),
  ('raf''s', 'Peter Gosik'),
  ('raf''s - new york', 'Peter Gosik'),
  ('ralph lauren restaurants', 'Courtney Kringstein'),
  ('ralph''s bar', 'Courtney Kringstein'),
  ('rams gate winery', 'Blakely Byrd'),
  ('range rover', 'Blakely Byrd'),
  ('range rover / purple pr - london', 'Blakely Byrd'),
  ('rcs - mexico', 'Peter Gosik'),
  ('rdlf', 'Blakely Byrd'),
  ('recess', 'Blakely Byrd + Melissa Crane-Baker'),
  ('red bull', 'Radhika Bansil'),
  ('red hook tavern', 'Peter Gosik'),
  ('red hook tavern - new york city', 'Peter Gosik'),
  ('red hook tavern - new york city, ny', 'Peter Gosik'),
  ('red hook tavern / sag harbor tavern - new york city, ny', 'Peter Gosik'),
  ('relevance international', 'Blakely Byrd'),
  ('replica', 'Blakely Byrd'),
  ('reseau', 'Blakely Byrd'),
  ('reserve padel - new york', 'Peter Gosik'),
  ('reserve padel design district - miami', 'Peter Gosik'),
  ('restaurant guy savoy', 'Joshua Stern'),
  ('restoration hardware', 'Blakely Byrd + Melissa Crane-Baker'),
  ('resy', 'Peter Gosik'),
  ('resy - new york city', 'Peter Gosik'),
  ('resy / opentable - new york / miami', 'Peter Gosik'),
  ('resy / toast - new york', 'Peter Gosik'),
  ('revolve', 'Peter Gosik'),
  ('revolve - new york', 'Peter Gosik'),
  ('rezdora', 'Peter Gosik'),
  ('rezdora - new york', 'Peter Gosik'),
  ('rezdora - new york city', 'Peter Gosik'),
  ('rh (restoration hardware)', 'Peter Gosik'),
  ('rh yacht', 'Peter Gosik'),
  ('richard anthony', 'Sasha Lambrecht'),
  ('rimowa', 'Blakely Byrd + Melissa Crane-Baker'),
  ('rivian', 'Blakely Byrd + Melissa Crane-Baker'),
  ('rizzoli', 'Blakely Byrd'),
  ('roam - new york', 'Peter Gosik'),
  ('roam - new york city', 'Peter Gosik'),
  ('rolex', 'Blakely Byrd'),
  ('rooam, toast - new york city', 'Peter Gosik'),
  ('rosaluna', 'Blakely Byrd + Melissa Crane-Baker'),
  ('roscioli', 'Joshua Stern'),
  ('roseblood', 'Blakely Byrd'),
  ('rovi / nopi', 'Natalia Bojanowicz'),
  ('rpm italian', 'Joshua Stern'),
  ('rpm seafood', 'Joshua Stern'),
  ('rpm steak', 'Joshua Stern'),
  ('rubin museum of himalayan art', 'Blakely Byrd'),
  ('rumor rose', 'Blakely Byrd + Melissa Crane-Baker'),
  ('sadelle''s', 'Peter Gosik'),
  ('sadelle''s - new york', 'Peter Gosik'),
  ('sadelle''s (bellagio)', 'Joshua Stern'),
  ('sadelle''s / carbone - new york', 'Peter Gosik'),
  ('saffy''s', 'Jordan Okun'),
  ('sag harbor tavern - sag harbor, ny', 'Peter Gosik'),
  ('saga', 'Peter Gosik'),
  ('saga - new york', 'Peter Gosik'),
  ('saint theo''s', 'Peter Gosik'),
  ('saint theo''s - new york', 'Peter Gosik'),
  ('saison hospitality', 'Peter Gosik'),
  ('sake no hana - new york', 'Peter Gosik'),
  ('salina', 'Natalia Bojanowicz'),
  ('salumeria rosi', 'Peter Gosik'),
  ('salumeria rosi - new york', 'Peter Gosik'),
  ('salumeria rosi & the wallace lounge - new york', 'Peter Gosik'),
  ('san lorenzo', 'Joshua Stern'),
  ('san sabino', 'Joshua Stern'),
  ('san vicente', 'Melissa Crane-Baker'),
  ('san vicente - los angeles', 'Knox Dobbins'),
  ('san vicente bungalows - los angeles', 'Knox Dobbins'),
  ('san vicente clubs', 'Knox Dobbins'),
  ('san vicente clubs - west hollywood', 'Knox Dobbins'),
  ('san vicente clubs (svb)', 'Knox Dobbins'),
  ('sanga (off-strip)', 'Joshua Stern'),
  ('sant ambroeus brookfield place - new york', 'Blakely Byrd'),
  ('santa cruz co.', 'Peter Gosik'),
  ('sappe', 'Peter Gosik'),
  ('sappe - new york', 'Peter Gosik'),
  ('sappe - new york city', 'Peter Gosik'),
  ('sappe - new york city, ny', 'Peter Gosik'),
  ('sappeisan - new york', 'Peter Gosik'),
  ('sappeisan - new york city', 'Peter Gosik'),
  ('sartiano''s', 'Andrew Goldberg'),
  ('sass cafe, the niwaki', 'Peter Gosik'),
  ('savona communications', 'Blakely Byrd'),
  ('scaramouche', 'Knox Dobbins'),
  ('scarpetta', 'Joshua Stern'),
  ('scorpios', 'Gaby'),
  ('scotts', 'Stefanie Bobinger'),
  ('seedlip', 'Blakely Byrd + Melissa Crane-Baker'),
  ('sequoia grove', 'Blakely Byrd'),
  ('serpentine galleries - new york', 'Peter Gosik'),
  ('serra', 'Natalia Bojanowicz'),
  ('sessions arts club', 'Knox Dobbins'),
  ('set steak & sushi - newport beach', 'Blakely Byrd'),
  ('sevenrooms', 'Peter Gosik'),
  ('sevenrooms - new york city', 'Peter Gosik'),
  ('sexy fish', 'Stefanie Bobinger'),
  ('shafer vineyards', 'Blakely Byrd'),
  ('shanghai me', 'Stefanie Bobinger'),
  ('shaw ross', 'Blakely Byrd'),
  ('shinji''s', 'Peter Gosik'),
  ('shinji''s - new york', 'Peter Gosik'),
  ('shinji''s - new york city', 'Peter Gosik'),
  ('shinji''s bar', 'Peter Gosik'),
  ('shinji''s bar - unknown', 'Peter Gosik'),
  ('shmone', 'Peter Gosik'),
  ('shmone - new york', 'Peter Gosik'),
  ('shrtlst', 'Blakely Byrd'),
  ('silversmith capital partners - boston', 'Knox Dobbins'),
  ('simpson''s in the strand', 'Courtney Kringstein + Natalia Bojanowicz + Stefanie Bobinger'),
  ('sip and guzzle nyc - new york city', 'Peter Gosik'),
  ('sipmargs', 'Blakely Byrd + Melissa Crane-Baker'),
  ('smithereens', 'Courtney Kringstein'),
  ('smithereens - new york city', 'Sasha Lambrecht'),
  ('snap', 'Blakely Byrd + Melissa Crane-Baker'),
  ('social studies - new york', 'Knox Dobbins'),
  ('social studies - new york city', 'Knox Dobbins'),
  ('socialista london', 'Courtney Kringstein'),
  ('soho house', 'Melissa Crane-Baker'),
  ('sol a sol - mexico city', 'Blakely Byrd'),
  ('sol a sol - new york', 'Peter Gosik'),
  ('solara society - south florida', 'Knox Dobbins'),
  ('soothr', 'Peter Gosik'),
  ('soothr - new york', 'Peter Gosik'),
  ('soothr nyc - new york city', 'Peter Gosik'),
  ('soraya', 'Stefanie Bobinger'),
  ('soto sake', 'Blakely Byrd + Melissa Crane-Baker'),
  ('south of france', 'Peter Gosik'),
  ('southern glazer''s', 'Blakely Byrd'),
  ('sovereign brands', 'Blakely Byrd'),
  ('spago', 'Jordan Okun'),
  ('spago (bellagio)', 'Joshua Stern'),
  ('sparrow + wolf (chinatown)', 'Joshua Stern'),
  ('spicy hospitality group', 'Sasha Lambrecht'),
  ('spoton', 'Peter Gosik'),
  ('spring place', 'Knox Dobbins'),
  ('spring place - new york', 'Knox Dobbins'),
  ('spring studios - new york', 'Peter Gosik'),
  ('ssm&l', 'Blakely Byrd'),
  ('st clements - london', 'Stefanie Bobinger'),
  ('st johns wood square - london', 'Stefanie Bobinger'),
  ('st. clement - london', 'Stefanie Bobinger'),
  ('st. clement (180 the thames) - london', 'Stefanie Bobinger'),
  ('stagecoach - unknown', 'Peter Gosik'),
  ('stagecoach demo', 'Peter Gosik'),
  ('starpower', 'Blakely Byrd'),
  ('starpower llc / ketel one - multi-city (hamptons, us)', 'Blakely Byrd'),
  ('stk', 'Joshua Stern'),
  ('straker''s', 'Courtney Kringstein'),
  ('stripe', 'Blakely Byrd + Melissa Crane-Baker'),
  ('stripe - new york', 'Knox Dobbins'),
  ('stripsteak', 'Joshua Stern'),
  ('stubborn seed (resorts world)', 'Joshua Stern'),
  ('stylus', 'Melissa Crane-Baker'),
  ('sumi', 'Courtney Kringstein'),
  ('sunlife - sag harbor', 'Sasha Lambrecht'),
  ('sunset hospitality group (~40 restaurants)', 'Stefanie Bobinger'),
  ('sunshine sachs morgan & lylis', 'Blakely Byrd'),
  ('superfrico', 'Joshua Stern'),
  ('supergoop', 'Blakely Byrd'),
  ('supergut', 'Blakely Byrd'),
  ('supper club - hamptons', 'Blakely Byrd'),
  ('supper club - unknown', 'Peter Gosik'),
  ('surface media - miami', 'Peter Gosik'),
  ('surface media - new york', 'Blakely Byrd'),
  ('surface media / hermes', 'Blakely Byrd'),
  ('sushi nakazawa', 'Peter Gosik'),
  ('sushi nakazawa - new york', 'Peter Gosik'),
  ('sushi noz (off-strip)', 'Joshua Stern'),
  ('sushi oku', 'Peter Gosik'),
  ('sushi oku - new york', 'Peter Gosik'),
  ('sushi samba', 'Stefanie Bobinger'),
  ('sushi samba london', 'Stefanie Bobinger'),
  ('sutton', 'Blakely Byrd'),
  ('sutton - the list', 'Blakely Byrd'),
  ('svb - new york', 'Knox Dobbins'),
  ('sw steakhouse (wynn)', 'Joshua Stern'),
  ('swiss wine guys', 'Blakely Byrd'),
  ('tag heuer', 'Blakely Byrd'),
  ('tag heuer / bpcm - monaco', 'Blakely Byrd'),
  ('taku', 'Peter Gosik'),
  ('taku mayfair - london', 'Peter Gosik'),
  ('talya hamptons', 'Courtney Kringstein'),
  ('tamarin', 'Natalia Bojanowicz'),
  ('tamarind', 'Courtney Kringstein'),
  ('tao - <unknown>', 'Peter Gosik'),
  ('tao - new york', 'Peter Gosik'),
  ('tao asian bistro', 'Joshua Stern'),
  ('tao downtown - new york', 'Peter Gosik'),
  ('tao group', 'Peter Gosik'),
  ('tao group hospitality', 'Knox Dobbins'),
  ('tatiana', 'Andrew Goldberg'),
  ('tatiana by kwame onwuachi', 'Andrew Goldberg'),
  ('tattu', 'Courtney Kringstein + Natalia Bojanowicz + Stefanie Bobinger'),
  ('tavern next door', 'Courtney Kringstein'),
  ('tcpr', 'Blakely Byrd'),
  ('temple bar - new york', 'Peter Gosik'),
  ('tequila centinela', 'Blakely Byrd'),
  ('tequila purisima', 'Blakely Byrd + Melissa Crane-Baker'),
  ('teremana', 'Blakely Byrd'),
  ('teremana tequila', 'Blakely Byrd + Melissa Crane-Baker'),
  ('termana tequila', 'Blakely Byrd + Melissa Crane-Baker'),
  ('thai diner', 'Peter Gosik'),
  ('thai diner - new york', 'Peter Gosik'),
  ('the arts club - london', 'Stefanie Bobinger'),
  ('the balvenie', 'Blakely Byrd'),
  ('the barbary - london', 'Peter Gosik'),
  ('the bastion collection', 'Peter Gosik'),
  ('the bull', 'Courtney Kringstein'),
  ('the carlton', 'Natalia Bojanowicz'),
  ('the chancery rosewood', 'Natalia Bojanowicz'),
  ('the clove club', 'Courtney Kringstein'),
  ('the concours club - new york city', 'Peter Gosik'),
  ('the core club - new york', 'Knox Dobbins'),
  ('the corner store', 'Peter Gosik'),
  ('the corner store - new york', 'Peter Gosik'),
  ('the delisle group', 'Blakely Byrd'),
  ('the dolli at acropolis', 'Blakely Byrd'),
  ('the dolli at acropolis - athens', 'Blakely Byrd'),
  ('the dover', 'Stefanie Bobinger'),
  ('the entourage group', 'Stefanie Bobinger'),
  ('the flower shop', 'Courtney Kringstein'),
  ('the garden table - michael mina', 'Joshua Stern'),
  ('the golden swan', 'Peter Gosik'),
  ('the golden swan - new york', 'Peter Gosik'),
  ('the golden swan - new york city', 'Peter Gosik'),
  ('the grill', 'Peter Gosik'),
  ('the grill - new york', 'Peter Gosik'),
  ('the hand & the eye', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('the hart', 'Courtney Kringstein'),
  ('the hero', 'Courtney Kringstein'),
  ('the huntington hotel', 'Peter Gosik'),
  ('the huntington hotel - san francisco', 'Peter Gosik'),
  ('the jazz club - <unknown>', 'Peter Gosik'),
  ('the jazz club - new york', 'Peter Gosik'),
  ('the jazz club - unknown', 'Peter Gosik'),
  ('the jazz club @ aman - new york', 'Peter Gosik'),
  ('the jazz club at aman new york - new york', 'Peter Gosik'),
  ('the joyce', 'Sasha Lambrecht'),
  ('the joyce - miami beach', 'Peter Gosik'),
  ('the joyce - new york', 'Sasha Lambrecht'),
  ('the joyce - new york city', 'Sasha Lambrecht'),
  ('the joyce - phoenix', 'Sasha Lambrecht'),
  ('the joyce - unknown', 'Sasha Lambrecht'),
  ('the joyce restaurant - new york city', 'Sasha Lambrecht'),
  ('the joyce restaurant - phoenix', 'Sasha Lambrecht'),
  ('the last agency', 'Blakely Byrd'),
  ('the lobster club', 'Peter Gosik'),
  ('the lobster club - new york', 'Peter Gosik'),
  ('the lounge - london', 'Peter Gosik'),
  ('the lounge at limelight', 'Peter Gosik'),
  ('the lowell hotel', 'Blakely Byrd'),
  ('the loyalist', 'Andrew Goldberg + Courtney Kringstein + Jordan Okun + Joshua Stern'),
  ('the macallan', 'Blakely Byrd'),
  ('the mayfair supper club', 'Joshua Stern'),
  ('the modern (moma / 53 w 53rd) - new york city', 'Peter Gosik'),
  ('the moore', 'Melissa Crane-Baker'),
  ('the musket room', 'Peter Gosik'),
  ('the musket room - new york', 'Peter Gosik'),
  ('the ned', 'Melissa Crane-Baker'),
  ('the ned - new york city', 'Knox Dobbins'),
  ('the ned - unknown', 'Knox Dobbins'),
  ('the office - miami', 'Peter Gosik'),
  ('the palomar', 'Peter Gosik'),
  ('the palomar - london', 'Peter Gosik'),
  ('the pelican', 'Courtney Kringstein'),
  ('the polo bar', 'Courtney Kringstein'),
  ('the sea the sea hackney - london', 'Peter Gosik'),
  ('the supper club - <unknown>', 'Blakely Byrd'),
  ('the supper club - new york', 'Blakely Byrd'),
  ('the supper club - new york city', 'Peter Gosik'),
  ('the supper club - unknown', 'Blakely Byrd'),
  ('the supper club (hamptons event) - hamptons, ny', 'Blakely Byrd'),
  ('the supper club inc - new york / miami', 'Peter Gosik'),
  ('the supper club inc / asg hospitality - new york / miami', 'Peter Gosik'),
  ('the supper club inc.', 'Peter Gosik'),
  ('the supper club inc. - <unknown>', 'Blakely Byrd'),
  ('the supper club inc. - desert/coachella valley', 'Peter Gosik'),
  ('the supper club inc. - indio / coachella valley', 'Peter Gosik'),
  ('the supper club inc. - indio / palm springs', 'Peter Gosik'),
  ('the supper club inc. - miami', 'Peter Gosik'),
  ('the supper club inc. - new york', 'Peter Gosik'),
  ('the supper club inc. - new york / miami', 'Peter Gosik'),
  ('the supper club inc. - new york city', 'Peter Gosik'),
  ('the supper club inc. - new york city / miami', 'Peter Gosik'),
  ('the supper club inc. - unknown', 'Peter Gosik'),
  ('the surf lodge - montauk', 'Sasha Lambrecht'),
  ('the twenty two', 'Knox Dobbins'),
  ('the twenty two - london', 'Knox Dobbins'),
  ('the tyger - new york', 'Peter Gosik'),
  ('the well', 'Melissa Crane-Baker'),
  ('the wilde', 'Melissa Crane-Baker'),
  ('the zero proof - los angeles', 'Blakely Byrd'),
  ('the zero proof / lapo''s - new york', 'Blakely Byrd'),
  ('third eye', 'Blakely Byrd'),
  ('this assembly - new york', 'Knox Dobbins'),
  ('three dots - chicago', 'Knox Dobbins'),
  ('three dots and a dash / bamboo room', 'Joshua Stern'),
  ('tiffany & co', 'Blakely Byrd'),
  ('time drop', 'Peter Gosik'),
  ('tito''s', 'Blakely Byrd + Melissa Crane-Baker'),
  ('tokyo record bar', 'Courtney Kringstein'),
  ('tolo - new york', 'Peter Gosik'),
  ('tom colicchio''s craftsteak', 'Joshua Stern'),
  ('topped off communications', 'Blakely Byrd'),
  ('topping rose house', 'Courtney Kringstein'),
  ('torrisi', 'Peter Gosik'),
  ('torrisi - new york', 'Peter Gosik'),
  ('torrisi - new york city', 'Peter Gosik'),
  ('torrisi (fontainebleau)', 'Joshua Stern'),
  ('townhome atx - austin', 'Blakely Byrd'),
  ('traded', 'Knox Dobbins'),
  ('tre dita', 'Joshua Stern'),
  ('trinity - london', 'Peter Gosik'),
  ('triptych management - unknown', 'Knox Dobbins'),
  ('trivoli tavern', 'Joshua Stern'),
  ('truman', 'Blakely Byrd'),
  ('tsc', 'Blakely Byrd'),
  ('tucci', 'Peter Gosik'),
  ('tucci - new york', 'Peter Gosik'),
  ('tumi', 'Blakely Byrd + Melissa Crane-Baker'),
  ('tusk bar / brass bar', 'Peter Gosik'),
  ('tutto', 'Courtney Kringstein'),
  ('tutto mare hamptons', 'Knox Dobbins'),
  ('tuxedo hospitality', 'Peter Gosik'),
  ('twist by pierre gagnaire (mandarin oriental)', 'Joshua Stern'),
  ('uchi', 'Peter Gosik'),
  ('uchi miami - miami', 'Peter Gosik'),
  ('una pizza napoletana - new york', 'Peter Gosik'),
  ('una vodka', 'Blakely Byrd'),
  ('unknown', 'Peter Gosik'),
  ('unknown - new york city', 'Peter Gosik'),
  ('unknown - unknown', 'Peter Gosik'),
  ('unknown (chris''s company)', 'Peter Gosik'),
  ('unkommon events - new york city', 'Peter Gosik'),
  ('unreal - london', 'Stefanie Bobinger'),
  ('unreal - united kingdom', 'Stefanie Bobinger'),
  ('unvrs', 'Marc L'),
  ('unwell', 'Blakely Byrd'),
  ('upspring', 'Blakely Byrd'),
  ('van cleef & arpels', 'Blakely Byrd'),
  ('vct | diablo, trivento', 'Blakely Byrd'),
  ('velvique', 'Blakely Byrd + Melissa Crane-Baker'),
  ('veranda - new york', 'Peter Gosik'),
  ('veranda at four seasons', 'Joshua Stern'),
  ('veronica mar', 'Blakely Byrd'),
  ('veuve clicquot', 'Blakely Byrd + Melissa Crane-Baker'),
  ('villa miramar - united kingdom', 'Stefanie Bobinger'),
  ('villa verde capri', 'Courtney Kringstein + Joshua Stern'),
  ('vintage wine estates', 'Blakely Byrd'),
  ('vintus wines', 'Blakely Byrd'),
  ('virgin music group', 'Knox Dobbins'),
  ('vita coco', 'Blakely Byrd + Melissa Crane-Baker'),
  ('vitra', 'Blakely Byrd'),
  ('vr vegas - las vegas', 'Peter Gosik'),
  ('vroom austin - austin', 'Peter Gosik'),
  ('vroom room - austin', 'Blakely Byrd'),
  ('vroom room atx - austin', 'Peter Gosik'),
  ('vroom room austin - austin', 'Blakely Byrd'),
  ('vueve clicquot', 'Blakely Byrd + Melissa Crane-Baker'),
  ('w south beach - bungalow 5 - miami', 'Peter Gosik'),
  ('wakuda (palazzo / venetian)', 'Joshua Stern'),
  ('warner brothers', 'Blakely Byrd + Melissa Crane-Baker'),
  ('waterloo sparkling water', 'Blakely Byrd + Melissa Crane-Baker'),
  ('waterworks', 'Blakely Byrd'),
  ('wayan', 'Courtney Kringstein'),
  ('waymo', 'Blakely Byrd + Melissa Crane-Baker'),
  ('wells fargo', 'Knox Dobbins'),
  ('wells fargo - new york', 'Knox Dobbins'),
  ('wes spirits', 'Blakely Byrd'),
  ('wheely', 'Knox Dobbins'),
  ('wheely - <unknown>', 'Knox Dobbins'),
  ('wheely - new york', 'Knox Dobbins'),
  ('whispering angel', 'Blakely Byrd + Melissa Crane-Baker'),
  ('whispering angel / chateau des clans (moet hennessy) - new york', 'Peter Gosik'),
  ('white house tavern', 'Courtney Kringstein'),
  ('whoop', 'Blakely Byrd + Melissa Crane-Baker'),
  ('wild by tart - london', 'Sasha Lambrecht'),
  ('wild fig', 'Courtney Kringstein'),
  ('wild group', 'Stefanie Bobinger'),
  ('wild tavern', 'Stefanie Bobinger'),
  ('wolf gang puck group', 'Blakely Byrd'),
  ('wolf gordon', 'Blakely Byrd'),
  ('wolffer estate', 'Blakely Byrd'),
  ('woody creek tavern', 'Courtney Kringstein'),
  ('wynn - las vegas', 'Sasha Lambrecht'),
  ('wynn las vegas', 'Sasha Lambrecht'),
  ('wynn las vegas - las vegas', 'Sasha Lambrecht'),
  ('xuclar', 'Marc L'),
  ('yahoo inc. - new york', 'Knox Dobbins'),
  ('yamasaki and bueno - new york city', 'Blakely Byrd'),
  ('yingtao', 'Sasha Lambrecht'),
  ('yingtao - new york', 'Sasha Lambrecht'),
  ('yingtao - new york city', 'Sasha Lambrecht'),
  ('yui edomae sushi (chinatown)', 'Joshua Stern'),
  ('yuki', 'Courtney Kringstein'),
  ('zakuska vodka', 'Blakely Byrd'),
  ('zefferino - monaco', 'Stefanie Bobinger'),
  ('zeffirino', 'Stefanie Bobinger'),
  ('zeffirino monaco', 'Stefanie Bobinger'),
  ('zeffirino monte carlo - monaco', 'Stefanie Bobinger'),
  ('zenith', 'Blakely Byrd'),
  ('zeno group', 'Blakely Byrd'),
  ('zenyara', 'Peter Gosik'),
  ('zenyara - <unknown>', 'Peter Gosik'),
  ('zenyara - coachella', 'Peter Gosik'),
  ('zenyara - coachella valley', 'Peter Gosik'),
  ('zenyara - coachella valley / indio', 'Peter Gosik'),
  ('zenyara - indio / coachella valley', 'Peter Gosik'),
  ('zenyara - indio / palm springs', 'Peter Gosik'),
  ('zenyara - mexico city', 'Peter Gosik'),
  ('zenyara - miami', 'Peter Gosik'),
  ('zenyara - new york', 'Peter Gosik'),
  ('zenyara - new york city', 'Peter Gosik'),
  ('zenyara - palm desert', 'Peter Gosik'),
  ('zenyara - unknown', 'Peter Gosik'),
  ('zephyr', 'Stefanie Bobinger'),
  ('zero bond', 'Knox Dobbins'),
  ('zero bond - new york', 'Knox Dobbins'),
  ('zero proof', 'Blakely Byrd'),
  ('zimmermann', 'Blakely Byrd + Melissa Crane-Baker'),
  ('zimmi''s', 'Peter Gosik'),
  ('zimmi''s - new york city', 'Peter Gosik'),
  ('zou zous', 'Joshua Stern'),
  ('zuma', 'Joshua Stern'),
  ('zuma cannes', 'Natalia Bojanowicz'),
  ('zuma dubai', 'Joshua Stern'),
  ('zuma london', 'Joshua Stern'),
  ('zuma mykonos', 'Joshua Stern + Marc L'),
  ('zz’s', 'Marc L')
) as m(venue_norm, owner)
where lower(trim(regexp_replace(d.venue, '\s+', ' ', 'g'))) = m.venue_norm;

update public.app_settings
set value = (
  select coalesce(jsonb_agg(distinct x order by x), '[]'::jsonb)
  from (
    select jsonb_array_elements_text(value) as x from public.app_settings where key = 'sales_leads'
    union
    select 'Andrew Goldberg'::text
    union
    select 'Ava Dagres'::text
    union
    select 'Blakely Byrd'::text
    union
    select 'Courtney Kringstein'::text
    union
    select 'Gaby'::text
    union
    select 'Gaby Espejo'::text
    union
    select 'Jordan Okun'::text
    union
    select 'Joshua Stern'::text
    union
    select 'Knox Dobbins'::text
    union
    select 'Marc L'::text
    union
    select 'Melissa Crane-Baker'::text
    union
    select 'Natalia Bojanowicz'::text
    union
    select 'Peter Gosik'::text
    union
    select 'Radhika Bansil'::text
    union
    select 'Sasha Lambrecht'::text
    union
    select 'Stefanie Bobinger'::text
  ) s
), updated_at = now()
where key = 'sales_leads';

commit;
