-- Dorsia BD pipeline — run in Supabase SQL Editor (Dashboard → SQL → New query)

-- ─── Settings (priority markets, allowed email domains) ───
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.app_settings (key, value) values
  ('priority_markets', '["New York","London","LA","Miami","Chicago","Dubai","SF"]'::jsonb),
  ('allowed_email_domains', '[]'::jsonb),
  ('restaurant_groups', '[]'::jsonb),
  ('market_list', '[]'::jsonb),
  ('sales_leads', '[]'::jsonb)
on conflict (key) do nothing;

-- Set allowed domains after deploy, e.g.:
-- update app_settings set value = '["dorsia.co","dorsia.com"]'::jsonb where key = 'allowed_email_domains';

-- ─── Deals ───
create table if not exists public.deals (
  id bigint generated by default as identity primary key,
  venue text not null,
  group_name text not null default '',
  tier text not null default '',
  market text not null default '',
  stage text not null default 'Lead',
  src_stage text not null default '',
  status text not null default 'Not a priority',
  owner text not null default '',
  last_contact text not null default '',
  blockers text not null default '',
  notes text not null default '',
  deal_value text not null default '',
  year1_arr text not null default '',
  billing text not null default '',
  contact text not null default '',
  website text not null default '',
  expected_close text not null default '',
  tasks jsonb not null default '[]'::jsonb,
  meetings jsonb not null default '[]'::jsonb,
  contacts jsonb not null default '[]'::jsonb,
  activity_notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists deals_stage_idx on public.deals (stage);
create index if not exists deals_owner_idx on public.deals (owner);
create index if not exists deals_market_idx on public.deals (market);

-- ─── Auth helper: authenticated + optional email domain allowlist ───
create or replace function public.is_bd_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    auth.uid() is not null
    and coalesce(auth.jwt()->>'email', '') <> ''
    and (
      not exists (
        select 1 from public.app_settings s
        where s.key = 'allowed_email_domains'
          and jsonb_array_length(s.value) > 0
      )
      or exists (
        select 1
        from public.app_settings s,
             jsonb_array_elements_text(s.value) as domain
        where s.key = 'allowed_email_domains'
          and lower(auth.jwt()->>'email') like '%@' || lower(domain)
      )
    );
$$;

-- ─── Row Level Security ───
alter table public.deals enable row level security;
alter table public.app_settings enable row level security;

drop policy if exists "bd read deals" on public.deals;
drop policy if exists "bd insert deals" on public.deals;
drop policy if exists "bd update deals" on public.deals;
drop policy if exists "bd delete deals" on public.deals;
drop policy if exists "bd read settings" on public.app_settings;
drop policy if exists "bd write settings" on public.app_settings;

create policy "bd read deals" on public.deals
  for select to authenticated using (public.is_bd_user());

create policy "bd insert deals" on public.deals
  for insert to authenticated with check (public.is_bd_user());

create policy "bd update deals" on public.deals
  for update to authenticated using (public.is_bd_user()) with check (public.is_bd_user());

create policy "bd delete deals" on public.deals
  for delete to authenticated using (public.is_bd_user());

create policy "bd read settings" on public.app_settings
  for select to authenticated using (public.is_bd_user());

create policy "bd write settings" on public.app_settings
  for all to authenticated using (public.is_bd_user()) with check (public.is_bd_user());

-- ─── updated_at trigger ───
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists deals_updated_at on public.deals;
create trigger deals_updated_at
  before update on public.deals
  for each row execute function public.set_updated_at();

drop trigger if exists app_settings_updated_at on public.app_settings;
create trigger app_settings_updated_at
  before update on public.app_settings
  for each row execute function public.set_updated_at();

-- Reset auto-id after bulk inserts that supply explicit ids (seed/import recovery)
create or replace function public.reset_deals_id_sequence()
returns void
language sql
security definer
set search_path = public
as $$
  select setval(
    pg_get_serial_sequence('public.deals', 'id'),
    coalesce((select max(id) from public.deals), 0) + 1,
    false
  );
$$;
